services:
  api:
    image: golang:latest
    working_dir: /app
    volumes:
      - ./playwright-docker/api:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - auth:/auth
      - logs:/logs
    command: sh -c "go run main.go"
    ports:
      - "${API_PORT}:8080"
    environment:
      - AUTH_DIR=/auth

  playwright:
    build: 
      dockerfile: ./playwright-docker/playwright.dockerfile
    volumes:
      - auth:/auth
      - logs:/logs

volumes:
  auth:
  logs:
